packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@embedded-postgres/darwin-arm64'
  - '@embedded-postgres/darwin-x64'
  - '@embedded-postgres/linux-arm'
  - '@embedded-postgres/linux-arm64'
  - '@embedded-postgres/linux-ia32'
  - '@embedded-postgres/linux-ppc64'
  - '@embedded-postgres/linux-x64'
  - '@embedded-postgres/windows-x64'
  - esbuild
